### ISSUE TITLE
Subversion of newline truncation using unicode characters

### ISSUE THREAD

**Issue by furnivall** [alphagov/notifications-utils#1119]
Hi there,

While looking at some template injection vulnerabilities, I've spotted that you can bypass newline truncation (defined [here](https://github.com/alphagov/notifications-utils/blob/88c57d5eb530b88794814e57249c2403227aa664/notifications_utils/markdown.py#L222) or [here](https://github.com/alphagov/notifications-utils/blob/88c57d5eb530b88794814e57249c2403227aa664/notifications_utils/formatters.py#L55)) by sending the dreaded unicode 'hangul filler' character in our personalisations.

This could be utilised by a dodgy character who wants to hide some portion of the email content (if, say, they've utilised template injection to create a phishing email)

This can be represented using the following unicode sequence: `&#x3164;`

The below screenshot shows how it appears in notify:

<img width="542" alt="image" src="https://github.com/alphagov/notifications-utils/assets/18507008/3c8e7bfc-4bd3-408f-a057-c502e8cb975a">

**Comment by quis** [comment]
Thanks for reporting @furnivall. This is fixed now (although the change will take a few days to roll out to all our apps).
